version: 0.2
            
phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - npm install
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - index.js
  discard-paths: yes